# tmux list-keys

# http://jonasjacek.github.io/colors/
set -g default-terminal "screen-256color" # colors!

set -g mouse on

unbind C-b
set-option -g prefix C-q
bind C-q send-prefix
set-option -g status-keys emacs

set-option -g allow-rename off
set -g renumber-windows on  # renumber windows when a window is closed

# theme
set-option -g status-right '[#h###S:#I:#P]'

set -g base-index 1         # start windows numbering at 1
setw -g pane-base-index 1   # make pane numbering consistent with windows

set -g status-bg black
set -g status-fg white

# https://github.com/gpakosz/.tmux/blob/master/.tmux.conf
# -------------------------------------------------------
set -g display-panes-time 100 # slightly longer pane indicators display time
set -g display-time 3000      # slightly longer status messages display time
set -g status-interval 10     # redraw status line every 10 seconds

# pane navigation
# -r repeatable
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

# move window
# -n no output
bind -n S-Left {
  swap-window -t -1
  previous-window
}
bind -n S-Right {
  swap-window -t +1
  next-window
}

# popup session alt+9(wezterm) & ctrl-o
bind-key -n C-o if-shell -F '#{==:#{session_name},popup}' \
    { detach-client } \
    { display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E 'tmux attach-session -t popup || tmux new-session -s popup' }

# reload config
bind r {
  source-file ~/.tmux.conf
  display-message done
}

# session Cmd-`
bind -n S-Up switch-client -p
bind -n S-Down switch-client -n

# kill current window (only if not the last window)
# 先检查window个数，只有一个就直接返回
bind -r x {
  if-shell '[ $(tmux list-windows | wc -l) -gt 1 ]' {
    select-window -t:-1
    select-window -t:+1
    kill-window
  }
}
